framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
            - assets/js-compiled/
        excluded_patterns:
          - "*/assets/ts/*"
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
