services:
    monolog.formatter.full_trace:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"
            - 'Y-m-d H:i:s'
            - true  # allow inline breaks
            - true  # ignore empty context and extra
            - true  # include stacktraces

monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.project_dir%/data/monolog/%kernel.environment%.log"
            level: error
            max-files: 5
            formatter: monolog.formatter.full_trace

